#include "mlir/IR/Attributes.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
// #include "mlir/IR/FunctionImplementation.h"

// Needed for autogenerated print/parse functions in HirTypes.cpp.inc
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/IR/DialectImplementation.h"

#include "Dialect/hir/Hir.h"
#include "Dialect/hir/HirDialect.h"
#include "Dialect/hir/HirTypes.h.inc"

using namespace mlir;
using namespace mlir::hir;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/hir/Hir.cpp.inc"

// include generated source code for types
#define GET_TYPEDEF_CLASSES
#include "Dialect/hir/HirTypes.cpp.inc"
