#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
// #include "mlir/IR/FunctionImplementation.h"

// Needed for autogenerated print/parse functions in NetqasmTypes.cpp.inc
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

#include "Dialect/Netqasm/Netqasm.h"
#include "Dialect/Netqasm/NetqasmDialect.h"
#include "Dialect/Netqasm/NetqasmTypes.h.inc"

using namespace mlir;
using namespace mlir::netqasm;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/Netqasm/Netqasm.cpp.inc"

// include generated source code for types
#define GET_TYPEDEF_CLASSES
#include "Dialect/Netqasm/NetqasmTypes.cpp.inc"
