#include "mlir/IR/Attributes.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
// #include "mlir/IR/FunctionImplementation.h"

// Needed for autogenerated print/parse functions in NetqasmTypes.cpp.inc
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/IR/DialectImplementation.h"

#include "Dialect/netqasm/Netqasm.h"
#include "Dialect/netqasm/NetqasmDialect.h"
#include "Dialect/netqasm/NetqasmTypes.h.inc"

using namespace mlir;
using namespace mlir::netqasm;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/netqasm/Netqasm.cpp.inc"

// include generated source code for types
#define GET_TYPEDEF_CLASSES
#include "Dialect/netqasm/NetqasmTypes.cpp.inc"

LogicalResult CallOp::verifySymbolUses(SymbolTableCollection &symbolTable)
{
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("callee");
    if (!fnAttr)
        return emitOpError("requires a 'callee' symbol reference attribute");
    SubroutineOp fn = symbolTable.lookupNearestSymbolFrom<SubroutineOp>(*this, fnAttr);
    if (!fn)
        return emitOpError() << "'" << fnAttr.getValue()
                             << "' does not reference a valid function";

    // Verify that the operand and result types match the callee.
    auto fnType = fn.getFunctionType();
    if (fnType.getNumInputs() != getNumOperands())
        return emitOpError("incorrect number of operands for callee");

    for (unsigned i = 0, e = fnType.getNumInputs(); i != e; ++i)
        if (getOperand(i).getType() != fnType.getInput(i))
            return emitOpError("operand type mismatch: expected operand type ")
                   << fnType.getInput(i) << ", but provided "
                   << getOperand(i).getType() << " for operand number " << i;

    if (fnType.getNumResults() != getNumResults())
        return emitOpError("incorrect number of results for callee");

    for (unsigned i = 0, e = fnType.getNumResults(); i != e; ++i)
        if (getResult(i).getType() != fnType.getResult(i))
        {
            auto diag = emitOpError("result type mismatch at index ") << i;
            diag.attachNote() << "      op result types: " << getResultTypes();
            diag.attachNote() << "function result types: " << fnType.getResults();
            return diag;
        }

    return success();
}

LogicalResult EntangleKeepOp::verifySymbolUses(SymbolTableCollection &symbolTable)
{
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote_node");
    if (!fnAttr)
        return emitOpError("requires a 'remote_node' symbol reference attribute");
    RemoteNodeOp fn = symbolTable.lookupNearestSymbolFrom<RemoteNodeOp>(*this, fnAttr);
    if (!fn)
        return emitOpError() << "'" << fnAttr.getValue()
                             << "' does not reference a valid remote node";

    return success();
}

LogicalResult SendMsgOp::verifySymbolUses(SymbolTableCollection &symbolTable)
{
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote_node");
    if (!fnAttr)
        return emitOpError("requires a 'remote_node' symbol reference attribute");
    RemoteNodeOp fn = symbolTable.lookupNearestSymbolFrom<RemoteNodeOp>(*this, fnAttr);
    if (!fn)
        return emitOpError() << "'" << fnAttr.getValue()
                             << "' does not reference a valid remote node";

    return success();
}

LogicalResult ReceiveMsgOp::verifySymbolUses(SymbolTableCollection &symbolTable)
{
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote_node");
    if (!fnAttr)
        return emitOpError("requires a 'remote_node' symbol reference attribute");
    RemoteNodeOp fn = symbolTable.lookupNearestSymbolFrom<RemoteNodeOp>(*this, fnAttr);
    if (!fn)
        return emitOpError() << "'" << fnAttr.getValue()
                             << "' does not reference a valid remote node";

    return success();
}