#include "QNet-C/QNet-c.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"

namespace py = pybind11;
using namespace mlir::python::adaptors;

static void registerQNetTypes(py::module &m) {
    /**
     * We create a type subclass that represents the qnet.qubit type of the dialect.
     * We name this class "QubitType", and also pass callbacks to the QNet C API functions
     * to determine if a type is qnet.qubit, and the ID of it (generated by tablegen)
     * WARNING: This "helper" method creates a python subclass that extends from qnet(mlir).ir.Type.
     * The generated class creates static methods that only allow creating a qubit Type
     * **by casting it from another one** (constructor QubitType(cast_from_type: qnet.it.Type))
     * which does not allow to create an instance of the QubitType "out of blue", as it can be
     * done with the built-in types like "i32", "index" or "tensor". These types use *manual*
     * python bindings to declare "get" methods that allow creating the type without casting it
     * from another type.
     */
    auto qubitType = mlir_type_subclass(m, "QubitType",
                                        mlirTypeIsAQubitType, mlirQubitTypeGetTypeID);
    /**
     * As a "workaround" of the "can-only-create-from-cast" problem, we declare a new function in
     * the class: "get", which receives the MlirContext object (qnet.ir.Context in python) and spawns
     * an instance of the type from it. This should suffice for out purposes.
     */
    qubitType.def_staticmethod(
            "get",
            [](MlirContext context) {
                return mlirQubitTypeGet(context);
            });
}

// This file will be compiled as the "_qnetTypes" python module, so we need
// to declare such module in the "name" argument of this macro
PYBIND11_MODULE(_qnetTypes, m) {
    // We declare a submodule called "qnet_types"
    auto qnetTypesM = m.def_submodule("qnet_types");

    // Registration of the QNet dialect under the "qir_types" module
    qnetTypesM.def(
        // We define a "register_dialect" function under the "qir_types" module
        "register_dialect",
        [](MlirContext context, bool load) {
            MlirDialectHandle handle = mlirGetDialectHandle__qnet__();
            mlirDialectHandleRegisterDialect(handle, context);
            if (load) {
                mlirDialectHandleLoadDialect(handle, context);
            }
        },
        py::arg("context") = py::none(), py::arg("load") = true);
    registerQNetTypes(qnetTypesM);
}
