#ifndef QOALAHOST_H
#define QOALAHOST_H

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Support/LogicalResult.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaHost.h.inc
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

using namespace mlir;

// QoalaHost uses NetQASM classes and vice versa; so we insert _forward_ class
// declarations so this file compiles correctly
#define GET_OP_FWD_DEFINES
#include "Dialect/NetQASM/NetQASM.h.inc"

#define GET_OP_CLASSES
#include "Dialect/QoalaHost/QoalaHost.h.inc"

#include "Dialect/QoalaHost/QoalaHostDialect.h"

#endif // QOALAHOST_H

#ifdef GET_ALLOWED_DIALECTS
// List of dialects allowed by the QoalaHost dialects
#undef GET_ALLOWED_DIALECTS
mlir::arith::ArithDialect,
mlir::memref::MemRefDialect,
mlir::cf::ControlFlowDialect,
mlir::tensor::TensorDialect,
mlir::affine::AffineDialect,
qoala::dialects::qoalahost::QoalaHostDialect
#endif