#ifndef QREMOTE_H
#define QREMOTE_H

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Support/LogicalResult.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaLir.h.inc
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

#define GET_OP_CLASSES
#include "Dialect/QRemote/QRemote.h.inc"

#include "Dialect/QRemote/QRemoteDialect.h"

#endif // QREMOTE_H
