#include "mlir/IR/Attributes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
#include "mlir/IR/FunctionImplementation.h"

// Needed for autogenerated print/parse functions in QoalaLirMTypes.cpp.inc
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/IR/DialectImplementation.h"

#include "Dialect/qoala_lir_m/QoalaLirM.h"
#include "Dialect/qoala_lir_m/QoalaLirMDialect.h"
#include "Dialect/qoala_lir_m/QoalaLirMTypes.h.inc"

using namespace mlir;
using namespace mlir::qoala_lir_m;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/qoala_lir_m/QoalaLirM.cpp.inc"

// include generated source code for types
#define GET_TYPEDEF_CLASSES
#include "Dialect/qoala_lir_m/QoalaLirMTypes.cpp.inc"
