#ifndef LIR_H
#define LIR_H

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Support/LogicalResult.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Interfaces/FunctionInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaLir.h.inc
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"

// FIRST include typedef classes, THEN op classes (latter needs decls of former)
#define GET_TYPEDEF_CLASSES
#include "Dialect/lir/LirTypes.h.inc"

#define GET_OP_CLASSES
#include "Dialect/lir/Lir.h.inc"

using namespace mlir;

#endif // LIR_H