#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/Support/Debug.h"

// Needed for autogenerated print/parse functions in QNetTypes.cpp.inc
#include "mlir/IR/DialectImplementation.h"

#include "Dialect/QNet/QNet.h"
#include "Dialect/QNet/QNetTypes.h.inc"

using namespace mlir;
using namespace qoala::dialects::qnet;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/QNet/QNet.cpp.inc"


LogicalResult SendIntsOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

LogicalResult RecvIntsOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

LogicalResult
SendFloatsOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

LogicalResult
RecvFloatsOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

LogicalResult EprsOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

LogicalResult
EprsMeasureOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
    // Check that the callee attribute was specified.
    auto fnAttr = (*this)->getAttrOfType<FlatSymbolRefAttr>("remote");
    if (!fnAttr)
        return emitOpError("requires a 'remote' symbol reference attribute");
    // Iteratively search on the parent SymbolTables
    for (auto *parent = getOperation()->getParentOp(); parent; parent = parent->getParentOp()) {
        if (auto nearest = symbolTable.lookupNearestSymbolFrom<RemoteOp>(parent, getRemoteAttr())) {
            return success();
        }
    }
    return emitOpError() << "'" << fnAttr.getValue()
                         << "' does not reference a valid remote node";
}

/* Parse and print functions "ported" from func.func */

ParseResult FuncOp::parse(OpAsmParser &parser, OperationState &result) {
    auto buildFuncType =
            [](Builder &builder, ArrayRef<Type> argTypes, ArrayRef<Type> results,
               function_interface_impl::VariadicFlag,
               std::string &) { return builder.getFunctionType(argTypes, results); };

    return function_interface_impl::parseFunctionOp(
            parser, result, /*allowVariadic=*/false,
            getFunctionTypeAttrName(result.name), buildFuncType,
            getArgAttrsAttrName(result.name), getResAttrsAttrName(result.name));
}

void FuncOp::print(OpAsmPrinter &p) {
    function_interface_impl::printFunctionOp(
            p, *this, /*isVariadic=*/false, getFunctionTypeAttrName(),
            getArgAttrsAttrName(), getResAttrsAttrName());
}