#ifndef HOST_H
#define HOST_H

#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/IR/BuiltinAttributes.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/IR/FunctionInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaLir.h.inc
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/CallInterfaces.h"

// FIRST include typedef classes, THEN op classes (latter needs decls of former)
#define GET_TYPEDEF_CLASSES
#include "Dialect/Host/HostTypes.h.inc"

#define GET_OP_CLASSES
#include "Dialect/Host/Host.h.inc"

using namespace mlir;

#endif // HOST_H