#ifndef NETQASM_H
#define NETQASM_H

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Support/LogicalResult.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaLir.h.inc
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"

using namespace mlir;

// NetQASM uses QoalaHost classes and vice versa; so we insert _forward_ class
// declarations so this file compiles correctly
// We insert these forward defines only because the `verifySymbolUses` function
// generated from the tblgen file (NetQASMOps.td) requires the qoalahost::Remote
// type to check the validity of the declared symbol
// An idea for the future to break this (circular) dependency is to place the
// remote declaration in a separate dialect.
#define GET_OP_FWD_DEFINES
#include "Dialect/QoalaHost/QoalaHost.h.inc"

#define GET_OP_CLASSES
#include "Dialect/NetQASM/NetQASM.h.inc"

#include "Dialect/NetQASM/NetQASMDialect.h"

#endif // NETQASM_H