#ifndef NETQASM_H
#define NETQASM_H

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Support/LogicalResult.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaLir.h.inc
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"

using namespace mlir;

// Remotes will be lowered to declarations in the qremote dialect
#include "Dialect/QRemote/QRemote.h"

#define GET_OP_CLASSES
#include "Dialect/NetQASM/NetQASM.h.inc"

#include "Dialect/NetQASM/NetQASMDialect.h"

#endif // NETQASM_H

#ifdef GET_ALLOWED_DIALECTS
// List of dialects allowed by the NetQASM dialects
#undef GET_ALLOWED_DIALECTS
mlir::arith::ArithDialect,
mlir::memref::MemRefDialect,
mlir::cf::ControlFlowDialect,
mlir::tensor::TensorDialect,
mlir::affine::AffineDialect,
qoala::dialects::netqasm::NetQASMDialect
#endif