#include "mlir/IR/Attributes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
#include "mlir/IR/FunctionImplementation.h"

// Needed for autogenerated print/parse functions in HostTypes.cpp.inc
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/IR/DialectImplementation.h"

#include "Dialect/Host/Host.h"
#include "Dialect/Host/HostDialect.h"
#include "Dialect/Host/HostTypes.h.inc"

using namespace mlir;
using namespace mlir::host;

// include generated source code for operations
#define GET_OP_CLASSES
#include "Dialect/Host/Host.cpp.inc"

// include generated source code for types
#define GET_TYPEDEF_CLASSES
#include "Dialect/Host/HostTypes.cpp.inc"
