#ifndef HIR_H
#define HIR_H

#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/IR/BuiltinAttributes.h"

// Needed for [FunctionOpInterface] in the .td file.
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Bytecode/BytecodeOpInterface.h"

// Needed for [NoMemoryEffect] in the .td file.
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Needed for autogenerated traits in QoalaHir.h.inc
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/CallInterfaces.h"

// FIRST include typedef classes, THEN op classes (latter needs decls of former)
#define GET_TYPEDEF_CLASSES
#include "Dialect/hir/HirTypes.h.inc"

#define GET_OP_CLASSES
#include "Dialect/hir/Hir.h.inc"

using namespace mlir;

#endif // HIR_H