name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "llvm-scip"
  SCIP_VERSION: "9.2.1"

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Retrieve LLVM referenced commit
        id: llvm-hash
        run: echo "LLVM_SHA=$(git rev-parse HEAD:llvm)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.llvm-hash.outputs.LLVM_SHA }}-${{ env.SCIP_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7.1.0
        with:
          context: .
          file: ./docker/llvm-scip/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SCIP_VERSION=${{ env.SCIP_VERSION }}
            LLVM_SHA=${{ steps.llvm-hash.outputs.LLVM_SHA }}
