name: Release Workflow
on:
  push:
    # Runs on pushing a tag iff the tag has the following format
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      version_override:
        description: "Version override"
        required: true
        type: string

jobs:
  lint-versions:
    name: Get LLVM and SCIP versions and run linter
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.llvm-scip-versions.outputs.IMAGE_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Compute Docker image name from LLVM and SCIP referenced versions
        id: llvm-scip-versions
        env:
          REGISTRY_NAME: "ghcr.io"
          IMAGE_BASE_NAME: "llvm-scip"
        run: |
          echo "IMAGE_NAME=${{ env.REGISTRY_NAME }}/${GITHUB_REPOSITORY_OWNER,,}/${{ github.event.repository.name }}-${{ env.IMAGE_BASE_NAME }}:$(cat .llvm_sha)-$(cat .scip_version)" >> $GITHUB_OUTPUT

      - name: Run clang-format check
        run: |
          chmod +x scripts/check-clang-format.sh 
          bash scripts/check-clang-format.sh

  build-and-test:
    name: Build artifacts for Python and test
    needs: [lint-versions]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python310, python311, python312]
    container:
      image: ${{ needs.lint-versions.outputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set build toolchain paths
        id: toolchain-paths
        shell: bash
        run: |
          echo "SCIP_DIR_IN_IMAGE=$(bash /toolchain/get_path.sh scip)" >> $GITHUB_ENV
          echo "MLIR_DIR_IN_IMAGE=$(bash /toolchain/get_path.sh mlir)" >> $GITHUB_ENV
          echo "VENV_DIR_IN_IMAGE=$(bash /toolchain/get_path.sh ${{ matrix.python-version }})" >> $GITHUB_ENV

      - name: Local version override
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=v${{ inputs.version_override }}" >> $GITHUB_ENV
          echo "QOALA_MLIR_VERSION=v${{ inputs.version_override }}" >> $GITHUB_ENV

      - name: Set version
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "QOALA_MLIR_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Configure and compile python wheel
        env:
          C_COMPILER_BIN: "clang-21"
          CXX_COMPILER_BIN: "clang++-21"
          LINKER_BIN: "ld.lld-21"
        shell: bash
        run: |
          source ${{ env.VENV_DIR_IN_IMAGE }}/bin/activate
          SKBUILD_CMAKE_ARGS="-DSCIP_DIR=${{ env.SCIP_DIR_IN_IMAGE }};-DMLIR_DIR=${{ env.MLIR_DIR_IN_IMAGE }};-DPython3_EXECUTABLE=${{ env.VENV_DIR_IN_IMAGE }}/bin/python;-DCMAKE_C_COMPILER=${{ env.C_COMPILER_BIN }};-DCMAKE_CXX_COMPILER=${{ env.CXX_COMPILER_BIN }};-DCMAKE_LINKER=${{ env.LINKER_BIN }}" \
          SETUPTOOLS_SCM_OVERRIDES_FOR_QOALA_MLIR='{local_scheme = "no-local-version"}' \
            python -m build --wheel

      - name: Test binary artifacts
        run: |
          export PATH=${{ env.MLIR_DIR_IN_IMAGE }}:$GITHUB_WORKSPACE/py-build/bin:$PATH
          llvm-lit --verbose test/

      - name: Prepare artifacts
        # We tar the artifacts, so they preseve the execution permission when expanding
        run: |
          mkdir -p /workspace/artifacts
          cd /workspace/artifacts
          cp $GITHUB_WORKSPACE/dist/*.whl .
          cp $GITHUB_WORKSPACE/py-build/bin/qoala-* .
          tar cvfz qoala-mlir-${{ env.QOALA_MLIR_VERSION }}-artifacts-${{ matrix.python-version }}.tgz *.whl qoala-*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          path: /workspace/artifacts/qoala-mlir-${{ env.QOALA_MLIR_VERSION }}-artifacts-${{ matrix.python-version }}.tgz
          name: qoala-mlir-${{ env.QOALA_MLIR_VERSION }}-artifacts-${{ matrix.python-version }}.tgz
          retention-days: 7
          if-no-files-found: error

  release:
    name: Publish Release
    needs: [ lint-versions, build-and-test ]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/qoala-mlir
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download built artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
          pattern: qoala-mlir-*
          merge-multiple: true

      - name: Create Linux binaries tag and prepare python wheels
        id: rename-artifact
        env:
          BINARIES_BASE_PKG_NAME: "qoala-mlir"
          BINARIES_ARCH: "linux-x86_64"
          GH_TOKEN: ${{ github.token }}
        run: |
          cd artifacts
          for file in *.tgz; do tar xvfz $file; done
          tar cvfz ${{ env.BINARIES_BASE_PKG_NAME}}-${{ github.ref_name }}-${{ env.BINARIES_ARCH }}.tar.gz *.whl qoala-*
          echo "ARTIFACT_NAME=${{ env.BINARIES_BASE_PKG_NAME}}-${{ github.ref_name }}-${{ env.BINARIES_ARCH }}.tar.gz" >> $GITHUB_OUTPUT
          echo $(pwd)
          ls -lah
          mkdir -p /release
          gh release create --title "Version ${{ github.ref_name }}" ${{ env.BINARIES_BASE_PKG_NAME}}-${{ github.ref_name }}-${{ env.BINARIES_ARCH }}.tar.gz *.whl

#      - name: Create GitHub Release and upload artifacts
#        uses: softprops/action-gh-release@v3.0.0
#        with:
#          name: "Release ${{ github.ref_name }}"
#          tag_name: ${{ github.ref_name }}
#          files: |
#            release/*.whl
#            release/${{ steps.rename-artifact.outputs.ARTIFACT_NAME }}

      - name: Upload python wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.14
        with:
          packages-dir: artifacts/release/

  release-test:
    name: Publish Release Test PyPI
    needs: [ lint-versions, build-and-test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/qoala-mlir
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download built artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
          pattern: qoala-mlir-*
          merge-multiple: true

      - name: Create Linux binaries tag and prepare python wheels
        id: rename-artifact
        env:
          BINARIES_BASE_PKG_NAME: "qoala-mlir"
          BINARIES_ARCH: "linux-x86_64"
          GH_TOKEN: ${{ github.token }}
        run: |
          cd artifacts
          for file in *.tgz; do tar xvfz $file; done
          tar cvfz ${{ env.BINARIES_BASE_PKG_NAME}}-v${{ inputs.version_override }}-${{ env.BINARIES_ARCH }}.tar.gz *.whl qoala-*
          echo "ARTIFACT_NAME=${{ env.BINARIES_BASE_PKG_NAME}}-${{ inputs.version_override }}-${{ env.BINARIES_ARCH }}.tar.gz" >> $GITHUB_OUTPUT
          echo $(pwd)
          ls -lah
          mkdir -p release
          cp *.whl release/
          gh release create --draft --title "Version ${{ inputs.version_override }}" ${{ env.BINARIES_BASE_PKG_NAME}}-v${{ inputs.version_override }}-${{ env.BINARIES_ARCH }}.tar.gz *.whl

#      - name: Create GitHub Release and upload artifacts
#        uses: softprops/action-gh-release@v3.0.0
#        with:
#          name: "Release ${{ inputs.version_override }}"
#          draft: true
#          files: |
#            release/*.whl
#            release/${{ steps.rename-artifact.outputs.ARTIFACT_NAME }}

      - name: Upload python wheels to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.14
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: artifacts/release/

